@baseUrl=http://localhost:4000/api
@resourceName=products

# Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###
# @name params
GET {{baseUrl}}/{{resourceName}}?color=white&price_gte=500

###
# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=2&_limit=3

###
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc

###
# @name fulltextSearch
GET {{baseUrl}}/{{resourceName}}?q=Carbonite

###
# @name searchName
GET {{baseUrl}}/{{resourceName}}?name_like=Tasty

###
# @name fsearchPrice
GET {{baseUrl}}/{{resourceName}}?price=778

###
# @name relationship
GET {{baseUrl}}/categories/8532f18a-401e-4131-900b-768548ffbc1f/products

###
# @name addNew
POST {{baseUrl}}/{{resourceName}}
content-type: application/json

{
  "categoryId": "683aca8a-bb4f-41c1-adef-1ecae7eb5793",
  "name": "Laptop",
  "color": "white",
  "price": 778,
  "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
  "thumbnail": "http://placeimg.com/400/400"
}

###
# @name update
PATCH {{baseUrl}}/{{resourceName}}/2RoOTSe
content-type: application/json

{
  "name": "Laptop New patch",
  "price": 788
}

###
# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2
content-type: application/json
